### ISSUE TITLE
trained model

### ISSUE THREAD

**Issue by KMoyle** [Kyungpyo-Kim/pointnet_kitti#1]
Hey Kyungpyo-Kim,

Awesome job altering pointnet to take raw point cloud. I was wondering if you would be able to email me a trained model, please?

Great work,
Kyle

**Comment by iris0329** [comment]
Hi, @Kyungpyo-Kim ,

Thanks for your sharing.
How about the performance ?
Could you please provide the pre-trained model ?

Thanks.

**Comment by Kyungpyo-Kim** [comment]
@KMoyle 
I'm sorry for late.
There is no trained model left.
However, since model training does not take much time, try training yourself. I remember that it took two or three hours to use the gtx1080.
Thank you for your interest.
@iris0329 
The performance was more than 80 percent on a kitti dataset, but overfitting was suspected.
It seems to be difficult to use as a general model.
